import {
  Apple,
  TreePine,
  Mountain,
  Gem,
  FlaskConical,
  Sword,
  LucideIcon,
} from "lucide-react";
import { Resources, ResourceConfig } from "./types";

export interface ResourceItem extends ResourceConfig {
  icon: LucideIcon;
  color: string;
  value: number;
}

export const getResourceItems = (resources: Resources): ResourceItem[] => [
  {
    key: "food",
    icon: Apple,
    label: "Food",
    value: resources?.food ?? 0,
    color: "text-green-500",
    description: "Essential resource for survival",
    formula: "(Village Base: +5/m + Tile Bonuses + Building Bonuses - Population Cost) × Speed",
    explanation:
      "Food is produced by your village (+5/m), improved tiles, and buildings. Each person consumes 1 food per minute. Production is multiplied by game speed. Hold Shift while hovering for detailed breakdown.",
  },
  {
    key: "wood",
    icon: TreePine,
    label: "Wood",
    value: resources?.wood ?? 0,
    color: "text-amber-600",
    description: "Building and crafting material",
    formula: "(Village Base: +3/m + Tile Bonuses + Building Bonuses) × Speed",
    explanation:
      "Wood is produced by your village (+3/m), improved tiles, and buildings. Used for construction and upgrades. Production is multiplied by game speed. Hold Shift while hovering for detailed breakdown.",
  },
  {
    key: "stone",
    icon: Mountain,
    label: "Stone",
    value: resources?.stone ?? 0,
    color: "text-slate-400",
    description: "Construction and defense material",
    formula: "(Village Base: +1/m + Tile Bonuses + Building Bonuses) × Speed",
    explanation:
      "Stone is produced by your village (+1/m), improved tiles, and buildings. Used for advanced construction. Production is multiplied by game speed. Hold Shift while hovering for detailed breakdown.",
  },
  {
    key: "diamond",
    icon: Gem,
    label: "Diamond",
    value: resources?.diamond ?? 0,
    color: "text-cyan-500",
    description: "Rare and valuable resource",
    formula: "(Tile Bonuses + Building Bonuses) × Speed",
    explanation:
      "Diamonds are obtained from special tiles and buildings. They are used for advanced upgrades and special purchases. Production is multiplied by game speed.",
  },
  {
    key: "technology",
    icon: FlaskConical,
    label: "Technology",
    value: resources?.technology ?? 0,
    color: "text-blue-500",
    description: "Research and advancement",
    formula: "(Tile Bonuses + Building Bonuses) × Speed",
    explanation:
      "Technology points are gained from specialized tiles and buildings (like libraries and military structures). Used for research and unlocking new capabilities. Production is multiplied by game speed.",
  },
  {
    key: "power",
    icon: Sword,
    label: "Power",
    value: resources?.power ?? 0,
    color: "text-red-500",
    description: "Military strength",
    formula: "(Unit Production) × Speed",
    explanation:
      "Power represents your military strength. It is generated by military units (warriors, archers, mages). Required to claim new tiles and defend your territory. Production is multiplied by game speed.",
  },
];
